### ISSUE TITLE
Field "userInformation" of type LoginResponseUserInformation in LoginResponseData has invalid value

### ISSUE THREAD

**Issue by PeterGrace** [mikey0000/PyMammotion#55]
when attempting to execute `tests/login_and_mqtt_test.py` I receive the below stacktrace.  My account was created via the google oauth flow with a password added afterwards, so my account does not have appear to have an e-mail address.

```
  $   poetry run python3 tests/login_and_mqtt_test.py
DEBUG:asyncio:Using selector: EpollSelector
{'code': 0, 'data': {'access_token': 'REDACTED', 'token_type': 'bearer', 'refresh_token': 'REDACTED', 'expires_in': 1295999, 'scope': 'read', 'grant_type': 'password', 'authorization_code': 'ehcVBQF8OyDGLWB8teKMoPuR', 'userInformation': {'userId': '649000000007067136', 'userAccount': '111111', 'authType': '0', 'areaCode': 'USA', 'domainAbbreviation': 'US'}, 'jti': 'e5a93faa-ae79-48de-a8db-50d81f744f03'}, 'msg': 'Request success'}
Traceback (most recent call last):
  File "<string>", line 45, in __mashumaro_from_dict__
  File "<string>", line 12, in __mashumaro_from_dict__
mashumaro.exceptions.MissingField: Field "email" of type str is missing in LoginResponseUserInformation instance

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pgrace/repos/PyMammotion/tests/login_and_mqtt_test.py", line 43, in <module>
    cloud_client = event_loop.run_until_complete(run())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.12/3.12.5/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/pgrace/repos/PyMammotion/tests/login_and_mqtt_test.py", line 25, in run
    luba_http = await LubaHTTP.login(session, EMAIL, PASSWORD)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pgrace/repos/PyMammotion/pymammotion/http/http.py", line 69, in login
    login_response_data = LoginResponseData.from_dict(data["data"])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 47, in __mashumaro_from_dict__
mashumaro.exceptions.InvalidFieldValue: Field "userInformation" of type LoginResponseUserInformation in LoginResponseData has invalid value {'userId': '649000000007067136', 'userAccount': 111111', 'authType': '0', 'areaCode': 'USA', 'domainAbbreviation': 'US'}
```

**Comment by petslane** [comment]
FYI, tokens still visible from history
<img width="296" alt="image" src="https://github.com/user-attachments/assets/a2dcd716-e4e0-431f-a228-bcdcd4e98cf9">

**Comment by PeterGrace** [comment]
:shrug: only the repo admins can delete the issue.  The base64 payload is mangled anyway, someone could put it through a base64 repairer but it would still only pop out part of the payload, and the oauth2 token, if the payload could be repaired enough to be usable, is only valid until the end of the month.

**Comment by mikey0000** [comment]
Fixed in make-em-mow PR
