### ISSUE TITLE
uhandled notifications?

### ISSUE THREAD

**Issue by ClockeNessMnstr** [mikey0000/PyMammotion#67]
Got the following error. I think it was for cutting disc jammed? 

Logger: homeassistant
Source: /usr/src/homeassistant/homeassistant/runner.py:147
First occurred: 2:38:51 PM (1 occurrences)
Last logged: 2:38:51 PM

Error doing job: Future exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion_cloud.py", line 116, in _on_mqtt_message
    await self._handle_mqtt_message(topic, payload)
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion_cloud.py", line 137, in _handle_mqtt_message
    await self._parse_mqtt_response(topic=topic, payload=payload)
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion_cloud.py", line 130, in _parse_mqtt_response
    await self.mqtt_message_event.data_event(event)
  File "/usr/local/lib/python3.12/site-packages/pymammotion/event/event.py", line 61, in data_event
    await self.on_data_event(data)
  File "/usr/local/lib/python3.12/site-packages/pymammotion/event/event.py", line 18, in __call__
    await asyncio.gather(*[handler(*args, **kwargs) for handler in self.__eventhandlers])
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion_cloud.py", line 292, in _parse_message_for_device
    await self._state_manager.notification(new_msg)
  File "/usr/local/lib/python3.12/site-packages/pymammotion/data/state_manager.py", line 56, in notification
    await self._update_nav_data(message)
  File "/usr/local/lib/python3.12/site-packages/pymammotion/data/state_manager.py", line 78, in _update_nav_data
    await self.gethash_ack_callback(nav_msg[1])
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/base.py", line 61, in datahash_response
    data_hash = self.mower.map.missing_hashlist.pop()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: pop from empty list

![Screenshot_20241005-145344](https://github.com/user-attachments/assets/c3ba2263-071d-4427-9067-58cc29d400c6)

**Comment by ClockeNessMnstr** [comment]
Except the cutting disc was not jammed and the error happened in home assistant a minute or two before it says it happened in the app

**Comment by ClockeNessMnstr** [comment]
1202 is the only novel one. I've been getting 327 and 328 in bursts. 1004/8 it was me checking the blades

**Comment by mikey0000** [comment]
Do you have a log of the notifications?

**Comment by ClockeNessMnstr** [comment]
I don't have debugging enabled. Is there still something I can copy/download?

**Comment by ClockeNessMnstr** [comment]
Oh actually is it because there's no "message"? There's a title and date but no other text to the notification

**Comment by mikey0000** [comment]
It only gives a code, dont worry if you can't get a log of the notification, I'll be able to get one.

**Comment by mikey0000** [comment]
This should be resolved now
